In [28]:
import pandas as pd
import numpy as np
import sqlite3

In [2]:


link = r"C:\Users\ashamail\OneDrive - Iowa State University\MD Simulation Research\SSTD Paper\Vessel Data\AIS_2022_01_01\AIS_2022_01_01.csv"
data = pd.read_csv(link)

In [10]:
uniqueMMSIs = len(np.unique(data["MMSI"]))
print(f"Total MMSI's = {uniqueMMSIs}, Total Points = {data.shape[0]}")

Total MMSI's = 14778, Total Points = 7239758

In [27]:
top5 = np.unique(data["MMSI"])[:5]
for x in top5:
    display(data[data["MMSI"] == x].head())

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TransceiverClass
6674950,0,2022-01-01T23:37:53,22.21441,-97.86972,0.0,186.7,288.0,CGC SPENCER,NaN,NWHE,55.0,15.0,82.0,12.0,4.3,55.0,A

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TransceiverClass
23280,1,2022-01-01T00:02:33,26.05740,-80.12843,0.0,283.2,511.0,MISS MARGARET,IMO0000000,NaN,37.0,NaN,21.0,6.0,0.0,0.0,B
37280,1,2022-01-01T00:05:33,26.05740,-80.12842,0.0,293.1,511.0,MISS MARGARET,IMO0000000,NaN,37.0,NaN,21.0,6.0,0.0,0.0,B
48044,1,2022-01-01T00:08:33,26.05742,-80.12839,0.0,289.4,511.0,MISS MARGARET,IMO0000000,NaN,37.0,NaN,21.0,6.0,0.0,0.0,B
173933,1,2022-01-01T00:35:34,26.05749,-80.12840,0.0,256.0,511.0,MISS MARGARET,IMO0000000,NaN,37.0,NaN,21.0,6.0,0.0,0.0,B
252317,1,2022-01-01T00:29:34,26.05744,-80.12838,0.0,254.1,511.0,MISS MARGARET,IMO0000000,NaN,37.0,NaN,21.0,6.0,0.0,0.0,B

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TransceiverClass
628092,11,2022-01-01T02:16:44,27.29225,-90.96757,0.2,247.5,511.0,CONSTITUTION,IMO0000007,GC 680,90.0,5.0,53.0,38.0,0.0,90.0,A
972667,11,2022-01-01T03:28:44,27.29220,-90.96759,0.1,272.8,511.0,CONSTITUTION,IMO0000007,GC 680,90.0,5.0,53.0,38.0,0.0,90.0,A
1135848,11,2022-01-01T03:46:43,27.29229,-90.96763,0.1,243.1,511.0,CONSTITUTION,IMO0000007,GC 680,90.0,5.0,53.0,38.0,0.0,90.0,A
1178214,11,2022-01-01T04:16:44,27.29216,-90.96754,0.2,244.4,511.0,CONSTITUTION,IMO0000007,GC 680,90.0,5.0,53.0,38.0,0.0,90.0,A
1244751,11,2022-01-01T04:19:44,27.29227,-90.96750,0.0,249.0,511.0,CONSTITUTION,IMO0000007,GC 680,90.0,5.0,53.0,38.0,0.0,90.0,A

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TransceiverClass
12446,111,2022-01-01T00:01:57,27.35378,-94.62550,0.2,258.7,511.0,BOOMVANG,IMO0000001,EB643,90.0,5.0,47.0,35.0,0.0,90.0,A
27993,111,2022-01-01T00:07:57,27.35373,-94.62546,0.1,248.2,511.0,BOOMVANG,IMO0000001,EB643,90.0,5.0,47.0,35.0,0.0,90.0,A
128590,111,2022-01-01T00:19:55,27.35378,-94.62536,0.2,235.1,511.0,BOOMVANG,IMO0000001,EB643,90.0,5.0,47.0,35.0,0.0,90.0,A
188409,111,2022-01-01T00:40:56,27.35369,-94.62539,0.2,227.5,511.0,BOOMVANG,IMO0000001,EB643,90.0,5.0,47.0,35.0,0.0,90.0,A
245038,111,2022-01-01T00:52:56,27.35370,-94.62533,0.1,231.8,511.0,BOOMVANG,IMO0000001,EB643,90.0,5.0,47.0,35.0,0.0,90.0,A

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TransceiverClass
21048,737255,2022-01-01T00:03:45,18.45952,-66.08801,0.1,298.5,511.0,PITTY,IMO0000000,ZGBC5,37.0,NaN,20.0,6.0,NaN,NaN,B
32198,737255,2022-01-01T00:06:42,18.45949,-66.08800,0.1,289.3,511.0,PITTY,IMO0000000,ZGBC5,37.0,NaN,20.0,6.0,NaN,NaN,B
58624,737255,2022-01-01T00:09:43,18.45948,-66.08803,0.0,282.0,511.0,PITTY,IMO0000000,ZGBC5,37.0,NaN,20.0,6.0,NaN,NaN,B
68097,737255,2022-01-01T00:15:42,18.45947,-66.08802,0.0,277.7,511.0,PITTY,IMO0000000,ZGBC5,37.0,NaN,20.0,6.0,NaN,NaN,B
72709,737255,2022-01-01T00:12:42,18.45947,-66.08803,0.0,277.2,511.0,PITTY,IMO0000000,ZGBC5,37.0,NaN,20.0,6.0,NaN,NaN,B

In [29]:
db = r"C:\Users\ashamail\OneDrive - Iowa State University\MD Simulation Research\SSTD Paper\Vessel Data\AISVesselTracks2022\AISVesselTracks2022\AISVesselTracks2022.sqlite"
# con = sqlite3.connect(db)

In [30]:
try:
     
    # Making a connection between sqlite3 
    # database and Python Program
    sqliteConnection = sqlite3.connect(db)
     
    # If sqlite3 makes a connection with python
    # program then it will print "Connected to SQLite"
    # Otherwise it will show errors
    print("Connected to SQLite")
 
    # Getting all tables from sqlite_master
    sql_query = """SELECT name FROM sqlite_master 
    WHERE type='table';"""
 
    # Creating cursor object using connection object
    cursor = sqliteConnection.cursor()
     
    # executing our sql query
    cursor.execute(sql_query)
    print("List of tables\n")
     
    # printing all tables list
    print(cursor.fetchall())
 
except sqlite3.Error as error:
    print("Failed to execute the above query", error)
     
finally:
   
    # Inside Finally Block, If connection is
    # open, we need to close it
    if sqliteConnection:
         
        # using close() method, we will close 
        # the connection
        sqliteConnection.close()
         
        # After closing connection object, we 
        # will print "the sqlite connection is 
        # closed"
        print("the sqlite connection is closed")

Connected to SQLite
List of tables

[('st_spatial_reference_systems',), ('st_aux_spatial_reference_systems',), ('sqlite_sequence',), ('st_geometry_columns',), ('st_vtspindex_interface',), ('AISVesselTracks2022',), ('st_spindex__AISVesselTracks2022_Shape',), ('st_spindex__AISVesselTracks2022_Shape_rowid',), ('st_spindex__AISVesselTracks2022_Shape_node',), ('st_spindex__AISVesselTracks2022_Shape_parent',)]
the sqlite connection is closed